/**
 * extract-lyrics.mjs
 *
 * Scans every MP3 in public/audio/, reads the embedded USLT (lyrics) ID3 tag,
 * and writes frontend/lib/lyrics.ts with a track_id → lyrics map.
 *
 * Run:  node scripts/extract-lyrics.mjs
 *
 * Safe to re-run any time — overwrites lib/lyrics.ts completely.
 * Tracks with no embedded lyrics are silently skipped.
 */

import { parseFile } from "music-metadata";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const AUDIO_DIR = path.join(ROOT, "public", "audio");
const CATALOG_PATH = path.join(ROOT, "lib", "staticCatalog.ts");
const OUTPUT_PATH = path.join(ROOT, "lib", "lyrics.ts");

// ── 1. Build audio_filename → track_id map from staticCatalog.ts ─────────────
const catalogSrc = fs.readFileSync(CATALOG_PATH, "utf8");
const idMap = {};
for (const match of catalogSrc.matchAll(
  /id:\s*"(track_\d+)"[^}]*audio_file:\s*"([^"]+)"/g,
)) {
  idMap[match[2]] = match[1];
}

// ── 2. Scan MP3s and extract lyrics ──────────────────────────────────────────
const files = fs
  .readdirSync(AUDIO_DIR)
  .filter((f) => f.toLowerCase().endsWith(".mp3"));

console.log(`Scanning ${files.length} MP3s in ${AUDIO_DIR}…\n`);

const found = {};
const missing = [];

for (const file of files) {
  const filePath = path.join(AUDIO_DIR, file);
  const trackId = idMap[file];

  let lyrics = null;
  try {
    const meta = await parseFile(filePath, { skipCovers: true });

    // music-metadata exposes lyrics in common.lyrics (array of objects or strings)
    const raw = meta.common.lyrics;
    if (Array.isArray(raw) && raw.length > 0) {
      const entry = raw[0];
      lyrics = typeof entry === "string" ? entry : (entry?.text ?? null);
    }
  } catch {
    // corrupt / unreadable file — skip silently
  }

  if (lyrics && lyrics.trim()) {
    const id = trackId ?? `/* unknown — audio file: ${file} */`;
    found[id] = lyrics.trim();
    console.log(`  ✓  ${file}  →  ${id}`);
  } else {
    missing.push(file);
  }
}

console.log(`\n${Object.keys(found).length} tracks with lyrics found.`);
console.log(`${missing.length} tracks with no embedded lyrics (skipped).\n`);

// ── 3. Write lib/lyrics.ts ───────────────────────────────────────────────────
const entries = Object.entries(found)
  .map(([id, text]) => {
    const escaped = text.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
    return `  "${id}": \`${escaped}\`,`;
  })
  .join("\n\n");

const output = `// Auto-generated by scripts/extract-lyrics.mjs — do not edit manually.
// Re-run the script after adding new tracks to pick up new lyrics.
// You can also add entries by hand for tracks without embedded metadata.
//
// Format:
//   "track_XXX": \`verse 1\\n\\nchorus\\n\\nverse 2\`

const LYRICS: Record<string, string> = {
${entries}
};

export function getLyrics(trackId: string): string | null {
  return LYRICS[trackId] ?? null;
}
`;

fs.writeFileSync(OUTPUT_PATH, output, "utf8");
console.log(`Written → ${OUTPUT_PATH}`);
