// Auto-generated by scripts/extract-lyrics.mjs — do not edit manually.
// Re-run the script after adding new tracks to pick up new lyrics.
// You can also add entries by hand for tracks without embedded metadata.
//
// Format:
//   "track_XXX": `verse 1\n\nchorus\n\nverse 2`

const LYRICS: Record<string, string> = {

};

export function getLyrics(trackId: string): string | null {
  return LYRICS[trackId] ?? null;
}
