// Full static catalog served from /public/audio/.
// lang: "en" | "es" | "spanglish" — drives bilingual DJ drop selection.

import type { Song } from "@/lib/types";

export const STATIC_CATALOG: Song[] = [
  { id: "track_001", lang: "en",        title: "1888",                        artist: "FlowSoundz",                   album: "Singles", genre: "R&B",          vibe: "late_night", duration_sec: 167, audio_file: "1888.mp3",                    public_audio_url: "/audio/1888.mp3",                    cover_file: "some1888.webp",            featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_002", lang: "en",        title: "3AM",                          artist: "FlowSoundz",                   album: "Singles", genre: "R&B Trap",      vibe: "late_night", duration_sec: 253, audio_file: "3am.mp3",                     public_audio_url: "/audio/3am.mp3",                     cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_003", lang: "spanglish", title: "No Te Imaginas",               artist: "FlowSoundz",                   album: "Singles", genre: "Hip-Hop",        vibe: "hype",       duration_sec: 134, audio_file: "5321_bobby_st_3.mp3",         public_audio_url: "/audio/5321_bobby_st_3.mp3",         cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_004", lang: "en",        title: "77",                           artist: "FlowSoundz",                   album: "Singles", genre: "Afrobeats",      vibe: "chill",      duration_sec: 149, audio_file: "77.mp3",                      public_audio_url: "/audio/77.mp3",                      cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_005", lang: "es",        title: "Algoritmo",                    artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "hype",       duration_sec: 147, audio_file: "algoritmo.mp3",               public_audio_url: "/audio/algoritmo.mp3",               cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_006", lang: "es",        title: "Apaga el Mundo",               artist: "FlowSoundz",                   album: "Singles", genre: "Reggaeton",      vibe: "chill",      duration_sec: 174, audio_file: "baby_tu_sabes.mp3",           public_audio_url: "/audio/baby_tu_sabes.mp3",           cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_007", lang: "es",        title: "Bandita (Remix)",              artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "hype",       duration_sec: 156, audio_file: "bandita_remix.mp3",           public_audio_url: "/audio/bandita_remix.mp3",           cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_008", lang: "en",        title: "Body Language",                artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "chill",      duration_sec: 194, audio_file: "body_language.mp3",           public_audio_url: "/audio/body_language.mp3",           cover_file: "bodylanguage.webp",        featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_009", lang: "es",        title: "Brindo Por Lo Que Fuimos",     artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "emotional",  duration_sec: 249, audio_file: "brindo_por_lo_que_fuimos.mp3", public_audio_url: "/audio/brindo_por_lo_que_fuimos.mp3", cover_file: "flowsoundz-artist.png",   featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_010", lang: "es",        title: "Cirujano Final",               artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "hype",       duration_sec: 142, audio_file: "cirujano_final.mp3",          public_audio_url: "/audio/cirujano_final.mp3",          cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_011", lang: "es",        title: "Conteo Official",              artist: "FlowSoundz",                   album: "Singles", genre: "Reggaeton",      vibe: "hype",       duration_sec: 231, audio_file: "conteo_official.mp3",         public_audio_url: "/audio/conteo_official.mp3",         cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_012", lang: "en",        title: "Conversation",                 artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "late_night", duration_sec: 257, audio_file: "conversation.mp3",            public_audio_url: "/audio/conversation.mp3",            cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_013", lang: "es",        title: "Doctora",                      artist: "FlowSoundz",                   album: "Singles", genre: "Reggaeton",      vibe: "hype",       duration_sec: 219, audio_file: "doctora.mp3",                 public_audio_url: "/audio/doctora.mp3",                 cover_file: "doctora.webp",             featured: true,  is_featured: true, is_playable: true, packaging_status: "ready" },
  { id: "track_014", lang: "es",        title: "Ese Olorcito Caramelo",        artist: "FlowSoundz",                   album: "Singles", genre: "Reggaeton",      vibe: "chill",      duration_sec: 164, audio_file: "ese_olorcito_caramelo.mp3",   public_audio_url: "/audio/ese_olorcito_caramelo.mp3",   cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_015", lang: "en",        title: "Essential",                    artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "chill",      duration_sec: 172, audio_file: "essential.mp3",               public_audio_url: "/audio/essential.mp3",               cover_file: "essential.webp",           featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_016", lang: "en",        title: "Far Away",                     artist: "FlowSoundz feat. Ezeqiel",     album: "Singles", genre: "R&B",            vibe: "emotional",  duration_sec: 128, audio_file: "far_away.mp3",                public_audio_url: "/audio/far_away.mp3",                cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_017", lang: "en",        title: "Find a Way",                   artist: "FlowSoundz feat. Adrian 🪐",  album: "Singles", genre: "R&B Soul",       vibe: "emotional",  duration_sec: 205, audio_file: "find_a_way.mp3",              public_audio_url: "/audio/find_a_way.mp3",              cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_018", lang: "en",        title: "Finji",                        artist: "FlowSoundz",                   album: "Singles", genre: "Afrobeats",      vibe: "chill",      duration_sec: 213, audio_file: "finji.mp3",                   public_audio_url: "/audio/finji.mp3",                   cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_020", lang: "en",        title: "Getting Down Tonight",         artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "late_night", duration_sec: 179, audio_file: "getting_down_tonight.mp3",    public_audio_url: "/audio/getting_down_tonight.mp3",    cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_021", lang: "en",        title: "Head in the Game",             artist: "FlowSoundz",                   album: "Singles", genre: "Hip-Hop",        vibe: "hype",       duration_sec: 161, audio_file: "head_in_the_game.mp3",        public_audio_url: "/audio/head_in_the_game.mp3",        cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_022", lang: "en",        title: "His Glory",                    artist: "FlowSoundz",                   album: "Singles", genre: "Gospel R&B",     vibe: "emotional",  duration_sec: 219, audio_file: "his_glory.mp3",               public_audio_url: "/audio/his_glory.mp3",               cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_023", lang: "es",        title: "Hola Me Presento",             artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "hype",       duration_sec: 198, audio_file: "hola_me_presento.mp3",        public_audio_url: "/audio/hola_me_presento.mp3",        cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_024", lang: "en",        title: "HOT IN THIS",                  artist: "FlowSoundz",                   album: "Singles", genre: "Hip-Hop",        vibe: "hype",       duration_sec: 119, audio_file: "hot_in_this.mp3",             public_audio_url: "/audio/hot_in_this.mp3",             cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_025", lang: "en",        title: "I Just Decided",               artist: "FlowSoundz feat. Ezeqiel",     album: "Singles", genre: "R&B",            vibe: "emotional",  duration_sec: 149, audio_file: "i_just_decided.mp3",          public_audio_url: "/audio/i_just_decided.mp3",          cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready", producer: "FlowSoundz" },
  { id: "track_026", lang: "en",        title: "I Was Just Playing",           artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "late_night", duration_sec: 255, audio_file: "i_was_just_playing.mp3",      public_audio_url: "/audio/i_was_just_playing.mp3",      cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_027", lang: "en",        title: "I'm Into That",                artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "chill",      duration_sec: 130, audio_file: "im_into_that.mp3",            public_audio_url: "/audio/im_into_that.mp3",            cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_028", lang: "es",        title: "Jungla de Concreto",           artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "hype",       duration_sec: 146, audio_file: "jungla_de_concreto.mp3",      public_audio_url: "/audio/jungla_de_concreto.mp3",      cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_029", lang: "en",        title: "Just Want to Dance",           artist: "FlowSoundz",                   album: "Singles", genre: "Afrobeats",      vibe: "chill",      duration_sec: 247, audio_file: "just_want_to_dance.mp3",      public_audio_url: "/audio/just_want_to_dance.mp3",      cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_030", lang: "es",        title: "La Baby Buena",                artist: "FlowSoundz",                   album: "Singles", genre: "Reggaeton",      vibe: "chill",      duration_sec: 194, audio_file: "la_baby_buena.mp3",           public_audio_url: "/audio/la_baby_buena.mp3",           cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_031", lang: "en",        title: "Lose Control",                 artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "late_night", duration_sec: 191, audio_file: "lose_control.mp3",            public_audio_url: "/audio/lose_control.mp3",            cover_file: "flowsoundz-artist.png",    featured: true,  is_featured: true, is_playable: true, packaging_status: "ready" },
  { id: "track_032", lang: "en",        title: "Love Sex and Pain",            artist: "FlowSoundz",                   album: "Singles", genre: "R&B Trap",       vibe: "late_night", duration_sec: 219, audio_file: "love_sex_and_pain.mp3",       public_audio_url: "/audio/love_sex_and_pain.mp3",       cover_file: "flowsoundz-artist.png",    featured: true,  is_featured: true, is_playable: true, packaging_status: "ready" },
  { id: "track_033", lang: "es",        title: "Mentirosa",                    artist: "FlowSoundz",                   album: "Singles", genre: "Reggaeton",      vibe: "hype",       duration_sec: 227, audio_file: "mentirosa.mp3",               public_audio_url: "/audio/mentirosa.mp3",               cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_034", lang: "es",        title: "No Confío",                    artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "emotional",  duration_sec: 185, audio_file: "no_confio.mp3",               public_audio_url: "/audio/no_confio.mp3",               cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_035", lang: "en",        title: "No More",                      artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "emotional",  duration_sec: 196, audio_file: "no_more.mp3",                 public_audio_url: "/audio/no_more.mp3",                 cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_036", lang: "en",        title: "No Where to Go",               artist: "FlowSoundz feat. Adrian 🪐",  album: "Singles", genre: "R&B",            vibe: "emotional",  duration_sec: 203, audio_file: "no_other.mp3",                public_audio_url: "/audio/no_other.mp3",                cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_037", lang: "es",        title: "No Soy Antisocial",            artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "hype",       duration_sec: 221, audio_file: "no_soy_antisocial.mp3",       public_audio_url: "/audio/no_soy_antisocial.mp3",       cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_038", lang: "en",        title: "O.M.W.",                       artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "late_night", duration_sec: 209, audio_file: "omw.mp3",                     public_audio_url: "/audio/omw.mp3",                     cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_039", lang: "en",        title: "On Ice",                       artist: "FlowSoundz",                   album: "Singles", genre: "Hip-Hop",        vibe: "chill",      duration_sec: 158, audio_file: "on_ice.mp3",                  public_audio_url: "/audio/on_ice.mp3",                  cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_040", lang: "es",        title: "Pinocho Gelato",               artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "hype",       duration_sec: 185, audio_file: "pinocho_gelato.mp3",          public_audio_url: "/audio/pinocho_gelato.mp3",          cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_041", lang: "en",        title: "Still Love",                   artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "emotional",  duration_sec: 204, audio_file: "still_love.mp3",              public_audio_url: "/audio/still_love.mp3",              cover_file: "still-got-love.webp",      featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_042", lang: "es",        title: "Te Quise en Silencio",         artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "emotional",  duration_sec: 335, audio_file: "te_quise_en_silencio.mp3",    public_audio_url: "/audio/te_quise_en_silencio.mp3",    cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_043", lang: "en",        title: "Therapy",                      artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "emotional",  duration_sec: 283, audio_file: "therapy.mp3",                 public_audio_url: "/audio/therapy.mp3",                 cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_044", lang: "spanglish", title: "Tú Me Fallaste",               artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "emotional",  duration_sec: 192, audio_file: "tu_me_fallaste.mp3",          public_audio_url: "/audio/tu_me_fallaste.mp3",          cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_045", lang: "en",        title: "You Ever Wanna Love Someone",  artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "emotional",  duration_sec: 158, audio_file: "you_ever_wanna_love_someone.mp3", public_audio_url: "/audio/you_ever_wanna_love_someone.mp3", cover_file: "flowsoundz-artist.png", featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_046", lang: "en",        title: "3 Times",                      artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "chill",      duration_sec: 287, audio_file: "3_times.mp3",                 public_audio_url: "/audio/3_times.mp3",                 cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_047", lang: "es",        title: "Doctora Alt",                  artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "hype",       duration_sec: 212, audio_file: "doctora_alt.mp3",             public_audio_url: "/audio/doctora_alt.mp3",             cover_file: "doctora.webp",             featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_048", lang: "en",        title: "MIA 2",                        artist: "FlowSoundz",                   album: "Singles", genre: "R&B Trap",       vibe: "late_night", duration_sec: 215, audio_file: "mia_2.mp3",                   public_audio_url: "/audio/mia_2.mp3",                   cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_049", lang: "en",        title: "Hold On To You",               artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "emotional",  duration_sec: 131, audio_file: "hold_on_to_you.mp3",          public_audio_url: "/audio/hold_on_to_you.mp3",          cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_050", lang: "spanglish", title: "Gangster Falso",               artist: "FlowSoundz",                   album: "Singles", genre: "Hip-Hop",        vibe: "hype",       duration_sec: 186, audio_file: "gangster_falso.mp3",          public_audio_url: "/audio/gangster_falso.mp3",          cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_051", lang: "es",        title: "Mentirosa (Naz T)",            artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "hype",       duration_sec: 227, audio_file: "mentirosa_naz_t.mp3",         public_audio_url: "/audio/mentirosa_naz_t.mp3",         cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_052", lang: "es",        title: "No Lo Niegues",                artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "emotional",  duration_sec: 90,  audio_file: "no_lo_niegues.mp3",           public_audio_url: "/audio/no_lo_niegues.mp3",           cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_053", lang: "spanglish", title: "Pero No Disparan",             artist: "FlowSoundz",                   album: "Singles", genre: "Hip-Hop",        vibe: "hype",       duration_sec: 243, audio_file: "pero_no_disparan.mp3",        public_audio_url: "/audio/pero_no_disparan.mp3",        cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_054", lang: "es",        title: "Quiere Mas",                   artist: "FlowSoundz",                   album: "Singles", genre: "Urban Latino",   vibe: "hype",       duration_sec: 160, audio_file: "quiere_mas_flowsoundz.mp3",   public_audio_url: "/audio/quiere_mas_flowsoundz.mp3",   cover_file: "flowsoundz-artist.png",    featured: true,  is_featured: true, is_playable: true, packaging_status: "ready" },
  { id: "track_056", lang: "en",        title: "DIIT",                         artist: "FlowSoundz",                   album: "Singles", genre: "Hip-Hop",        vibe: "hype",       duration_sec: 137, audio_file: "diit.mp3",                    public_audio_url: "/audio/diit.mp3",                    cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
  { id: "track_057", lang: "spanglish", title: "Sin Alivio a Toribo",          artist: "FlowSoundz",                   album: "Singles", genre: "R&B",            vibe: "emotional",  duration_sec: 225, audio_file: "sin_alivio_a_toribo.mp3",     public_audio_url: "/audio/sin_alivio_a_toribo.mp3",     cover_file: "flowsoundz-artist.png",    featured: false, is_playable: true, packaging_status: "ready" },
];

export function getStaticCatalog(vibe?: string): Song[] {
  if (!vibe || vibe === "all") return STATIC_CATALOG;
  const filtered = STATIC_CATALOG.filter((s) => s.vibe === vibe);
  return filtered.length > 0 ? filtered : STATIC_CATALOG;
}
